apiVersion: v1
kind: Service
metadata:
  name: pub-beersale
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 9085
      targetPort: 9085
  selector:
    app: pub-beersale