apiVersion: v1
kind: Service
metadata:
  name: pub-visitors
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9083
      targetPort: 9083
  selector:
    app: pub-visitors